# Generated by Django 4.0.2 on 2022-10-23 04:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posthand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postapi',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
